default: &default
  adapter: sqlserver
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 58307
  username: ""
  password: ""
  trust_server_certificate: true

development:
  <<: *default
  database: companies_api_development

test:
  <<: *default
  database: companies_api_test

production:
  <<: *default
  database: companies_api_production
